apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: ignis_org
      defaultBucket: ignis_bucket
    secureJsonData:
      token: ignis_secret_token_123
    isDefault: true
